INSERT INTO BANK(NAME) VALUES
('Sber');
INSERT INTO BANK(NAME) VALUES
('Alpha');
INSERT INTO BANK(NAME) VALUES
('VTB');
INSERT INTO BANK(NAME) VALUES
('Tinkoff');
INSERT INTO CLIENT(NAME, PHONE, EMAIL, PASSPORT, BANK_ID) VALUES
('Danil', '+79874', 'dan@ya.ru', '54896', 1);
INSERT INTO CLIENT(NAME, PHONE, EMAIL, PASSPORT, BANK_ID) VALUES
('Anton', '+79874', 'dan@ya.ru', '548961', 2);
INSERT INTO CLIENT(NAME, PHONE, EMAIL, PASSPORT, BANK_ID) VALUES
('Anton', '+79874', 'dan@ya.ru', '548962', 3);
INSERT INTO CLIENT(NAME, PHONE, EMAIL, PASSPORT, BANK_ID) VALUES
('Anton', '+79874', 'dan@ya.ru', '548963', 3);
INSERT INTO CREDIT(NAME, LIMIT, PERCENT, BANK_ID) VALUES
('AutoCredit', '150000', '20', 1);