DROP SCHEMA PUBLIC CASCADE;

create table BANK
(
    ID      INTEGER generated by default as identity(start with 1) primary key,
    NAME    VARCHAR(32) NOT NULL
);

create table CLIENT
(
    ID       INTEGER generated by default as identity(start with 1) primary key,
    NAME     VARCHAR(32) not null,
    PHONE    VARCHAR(32) not null,
    EMAIL    VARCHAR(32) not null,
    PASSPORT VARCHAR(32) not null,
    BANK_ID  INTEGER NOT NULL REFERENCES BANK(ID) ON DELETE CASCADE
);

create table CREDIT
(
    ID          INTEGER generated by default as identity(start with 1) primary key,
    BANK_ID     INTEGER NOT NULL REFERENCES BANK(ID) ON DELETE CASCADE,
    LIMIT       INTEGER not null,
    PERCENTAGE  INTEGER not null
);

create table OFFER
(
    ID INTEGER generated by default as identity(start with 1) primary key,
    CLIENT_ID INTEGER NOT NULL REFERENCES CLIENT(ID) ON DELETE CASCADE,
    CREDIT_ID INTEGER NOT NULL REFERENCES CREDIT(ID) ON DELETE CASCADE,
    CREDIT_SUM INTEGER not null,
    PAYMENT_DATE DATE not null,
    PAYMENT INTEGER,
    BODY_SUM INTEGER,
    PERCENTAGE_SUM  INTEGER
)

